services:
  eclipse_next:
    container_name: eclipse_next
    restart: always
    image: node:20.10.0
    ports:
      - 4000:3000
    environment: 
      - PORT=3000
      - API_URL=http://eclipse_api:3007  # Container-to-container communication
    volumes:
      - ./:/usr/src/eclipse-next
    working_dir: /usr/src/eclipse-next
    networks:
      - monorepo-network  # CHANGE THIS LINE
    command: bash -c "yarn && yarn run build && yarn run start"

networks:
  monorepo-network:  # CHANGE THIS LINE
    external: true     # Reference existing network